version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-djs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-djs_pw}
      - POSTGRES_DB=${POSTGRES_DB:-djs}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://djs:djs_pw@db:5432/djs}
      - JWT_SECRET=${JWT_SECRET:-CHANGE_ME_DEV_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES:-1440}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
