name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - 'Dockerfile.backend'
      - 'docker-compose.yml'
      - 'requirements.txt'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/worktools

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
